# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

@pytest.fixture
def setup():
    driver = webdriver.Chrome()
    yield driver
    driver.quit()

def test_login(setup):
    driver = setup
    driver.get("http://localhost:5173/")
    driver.maximize_window()
    time.sleep(2)
    driver.find_element(By.CSS_SELECTOR, ".-bg--color-semidark-violet").click()
    time.sleep(1)
    driver.find_element(By.ID, "username").click()
    time.sleep(1)
    driver.find_element(By.ID, "username").send_keys("mate@gmail.com")
    time.sleep(1)
    driver.find_element(By.ID, "password").click()
    time.sleep(1)
    driver.find_element(By.ID, "password").send_keys("(Abc123)")
    time.sleep(2)
    driver.find_element(By.NAME, "action").click()
    time.sleep(5)
    assert "Inventomate | Home" in driver.title
