# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select


@pytest.fixture
def setup():
    driver = webdriver.Chrome()
    yield driver
    driver.quit()

def test_newTrends(setup):
    driver = setup
    driver.get("http://localhost:5173/")
    driver.maximize_window()
    time.sleep(2)
    driver.find_element(By.CSS_SELECTOR, ".-bg--color-semidark-violet").click()
    time.sleep(1)
    driver.find_element(By.ID, "username").click()
    time.sleep(1)
    driver.find_element(By.ID, "username").send_keys("mate@gmail.com")
    time.sleep(1)
    driver.find_element(By.ID, "password").click()
    time.sleep(1)
    driver.find_element(By.ID, "password").send_keys("(Abc123)")
    time.sleep(1)
    driver.find_element(By.NAME, "action").click()
    time.sleep(4)
    driver.find_element(By.LINK_TEXT, "Company").click()
    time.sleep(2)
    driver.find_element(By.LINK_TEXT, "Next Orders").click()
    time.sleep(2)
    select_element = driver.find_element(By.ID, "select_branch")
    select = Select(select_element)
    time.sleep(1)
    select.select_by_index(1)
    time.sleep(2)
    element = driver.find_element(By.XPATH, "//button[contains(text(), 'Suggestion For Next Orders')]")
    element.click()
    WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(), 'Suggestion For Next Orders')]")))
    time.sleep(3)
    enlace = driver.find_element(By.ID, "0")
    enlace.click()
    time.sleep(2)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight)")
    time.sleep(3)
    driver.execute_script("window.scrollTo(document.body.scrollHeight, 0)")
    time.sleep(3)